#!/bin/bash

MONPROG_1=./tree_based_model.py
MONPROG_2=./parameters_tuning.py

chmod +x $MONPROG_1
chmod +x $MONPROG_2

rm -rf OAR.*
rm -rf log-NX*
echo DEBUT
date
$MONPROG_1 > tree_log 2>&1
$MONPROG_2 > parameters_log 2>&1
date
echo FIN